### ISSUE TITLE
[JP typedoc] Custom tags - every character appears on a new line.

### ISSUE THREAD

**Issue by randriova** [IgniteUI/igniteui-typedoc-theme#11]
Navigate to any component page that contains custom tags, e.g. [https://jp.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxcolumnlayoutcomponent.html#cellclasses](IgxColumnLayoutComponent). 

Tags appear as follows:
![image](https://user-images.githubusercontent.com/54146583/79842639-c8dbdb80-83c1-11ea-8140-eab103dafc36.png)
Same tag in EN Docs:
![image](https://user-images.githubusercontent.com/54146583/79842682-d4c79d80-83c1-11ea-9fe1-aacecd31c192.png)

**Comment by Aleksandyr** [comment]
This is due to the latest updates of the theme moving every tag and comment on a new line.
Currently, this is not possible to be resolved as we strive to achieve better formating when there are plenty of code snippets and tag comments.
