### ISSUE TITLE
Мissing global strings when doc is built

### ISSUE THREAD

**Issue by Aleksandyr** [IgniteUI/igniteui-typedoc-theme#18]
String in the header, toc, breadcrumb, etc. are missing when a documentation is built.

**Comment by zdrawku** [comment]
@radomirchev we will use this issue to create two theme versions - one for IG usage and another one for external usage. Currently, the theme is coupled with igniteui-agnular library and this prevents us to use it for other projects like the dock-manager API generation.

**Comment by Aleksandyr** [comment]
This issue will be fixed by #15
